apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: cluster-network-access
spec:
  reportType: network-access
  endpoints:
    namespaces:
      names: ["storefront", "default"]
  schedule: 0 * * * *
